import { ROLES } from "./roles";
import { PERMISSOES } from "./permissoes";

export const ROLE_PERMISSIONS = {
  [ROLES.GESTOR]: [
    PERMISSOES.PESQUISAR,
    PERMISSOES.CADASTRAR_NORMA,
    PERMISSOES.CADASTRAR_VERSAO,
    PERMISSOES.VISUALIZAR,
    PERMISSOES.SOLICITAR,
    PERMISSOES.CADASTRAR_USUARIO,
    PERMISSOES.EDITAR_USUARIO,
    PERMISSOES.VISUALIZAR_USUARIO,
  ],

  [ROLES.ENGENHEIRO]: [
    PERMISSOES.PESQUISAR,
    PERMISSOES.VISUALIZAR,
    PERMISSOES.SOLICITAR,
    PERMISSOES.EDITAR_USUARIO,
  ],

  [ROLES.VISUALIZADOR]: [
    PERMISSOES.PESQUISAR,
    PERMISSOES.VISUALIZAR,
    PERMISSOES.SOLICITAR,
    PERMISSOES.EDITAR_USUARIO,
  ],
};