import { ROLES } from "./roles";
import { PERMISSOES } from "./permissoes";

export const ROLE_PERMISSIONS = {
  [ROLES.GESTOR]: [
    PERMISSOES.PESQUISAR,
    PERMISSOES.CADASTRAR_NORMA,
    PERMISSOES.CADASTRAR_VERSAO,
    PERMISSOES.VISUALIZAR,
    PERMISSOES.SOLICITAR,
    PERMISSOES.SOLICITAR_NOTA,
    PERMISSOES.CADASTRAR_USUARIO,
    PERMISSOES.EDITAR_USUARIO,
    PERMISSOES.VISUALIZAR_USUARIOS,
    PERMISSOES.VISUALIZAR_SOLICITACOES,
    PERMISSOES.CADASTRAR_TAG,
    PERMISSOES.VISUALIZAR_NOTAS,
  ],

  [ROLES.ENGENHEIRO]: [
    PERMISSOES.PESQUISAR,
    PERMISSOES.VISUALIZAR,
    PERMISSOES.SOLICITAR,
    PERMISSOES.SOLICITAR_NOTA,
    PERMISSOES.EDITAR_USUARIO,
    PERMISSOES.VISUALIZAR_SOLICITACOES,
    PERMISSOES.VISUALIZAR_NOTAS,
  ],

  [ROLES.VISUALIZADOR]: [
    PERMISSOES.PESQUISAR,
    PERMISSOES.VISUALIZAR,
    PERMISSOES.SOLICITAR,
    PERMISSOES.SOLICITAR_NOTA,
    PERMISSOES.EDITAR_USUARIO,
    PERMISSOES.VISUALIZAR_NOTAS,
  ],
};
