export const areasTecnicas = [
    "Mecânica",
    "Hidráulica",
    "Elétrica",
    "Eletrônica",
    "Aviônicos",
    "Estruturas Aeronáuticas",
    "Motores",
    "Propulsão",
    "Pneumática",
    "Combustível",
    "Trem de Pouso",
    "Sistemas de Controle de Voo",
    "Navegação",
    "Comunicação",
    "Instrumentação",
    "Pressurização",
    "Ar-condicionado",
    "Sistemas Anti-gelo",
    "Sistemas de Oxigênio",
    "Iluminação",
    "Cabine",
    "Interior de Aeronaves",
    "Pintura Aeronáutica",
    "Corrosão",
    "Materiais Compostos",
    "Soldagem",
    "Usinagem",
    "Manutenção Preventiva",
    "Manutenção Corretiva",
    "Inspeção",
    "Qualidade",
    "Segurança Operacional",
    "Segurança de Voo",
    "Fatores Humanos",
    "Documentação Técnica",
    "Certificação",
    "Regulamentação",
    "Engenharia Aeronáutica",
    "Produção Aeronáutica",
    "Montagem",
    "Logística Aeronáutica",
    "Suprimentos",
    "Armazenamento",
    "Ensaios Não Destrutivos (END)",
    "Software Embarcado",
    "Sistemas Embarcados",
    "Automação",
    "Telecomunicações",
    "Aerodinâmica",
    "Balanceamento",
    "Estruturas Metálicas",
    "Estruturas Compósitas",
    "Processos Industriais",
    "Ferramentaria",
    "Calibração",
    "Metrologia",
    "Gestão da Manutenção",
    "Confiabilidade",
    "Rastreabilidade",
    "Meio Ambiente",
    "Sustentabilidade",
    "Operações de Solo",
    "Operações Aéreas",
    "Checklist Operacional",
    "Treinamento Técnico",
  ];